[workspace]
resolver = "2"
members = ["ssm-lib", "session-manager-plugin"]

[workspace.dependencies]
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
log = "0.4.26"
serde_json = "1.0.140"
thiserror = "2.0.12"
