[package]
name = "session-manager-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
ssm-lib = { path = "../ssm-lib" }
thiserror = { workspace = true }
