name: CI
run-name: CI ${{ github.actor }} ${{ github.ref_name }}

on:
  push:
    branches: "*"
    paths:
      - .github/**
      - session-manager-plugin/**
      - ssm-lib/**
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: master
    paths:
      - .github/**
      - session-manager-plugin/**
      - ssm-lib/**
      - Cargo.toml
      - Cargo.lock

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-nextest
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo nextest run