name: CI
run-name: CI ${{ github.actor }} ${{ github.ref_name }}

on:
  push:
    branches: "*"
    paths:
        - src/**
        - Cargo.toml
        - Cargo.lock
  pull_request:
    branches: master
    paths:
        - src/**
        - Cargo.toml
        - Cargo.lock

env:
  CARGO_TERM_COLOR: always

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
            - name: Run tests
              run: cargo test --verbose