name: CI
run-name: CI ${{ github.actor }} ${{ github.ref_name }}

on:
  pull_request:
    branches: master
    paths:
      - .github/**
      - session-manager-plugin/**
      - ssm-lib/**
      - Cargo.toml
      - Cargo.lock

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-nextest
          components: clippy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Lint
        run: cargo clippy --workspace
      - name: Run tests
        run: cargo nextest run